version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo-tasks-mongodb
    ports:
     - "27017:27017"
    volumes:
     - mongo-data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=todo-tasks

volumes:
  mongo-data:
    driver: local